"""empty message

Revision ID: 356754e9ce28
Revises: 984fa0a50ef5
Create Date: 2023-12-10 15:41:02.370145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356754e9ce28'
down_revision: Union[str, None] = '984fa0a50ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'about')
    # ### end Alembic commands ###
