"""empty message

Revision ID: 3f04e3499c26
Revises: 356754e9ce28
Create Date: 2023-12-10 16:02:15.200393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f04e3499c26'
down_revision: Union[str, None] = '356754e9ce28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'price')
    # ### end Alembic commands ###
